### ISSUE TITLE
developerguide/customizing should mention adding After

### ISSUE THREAD

**Issue by mak001** [dynamic/silverstripe-locator#180]
Should add a small blurb near the top about needing to add 
```yml
---
Name: config-name
After:
  - locator
---
```
before the needed configuration changes
