### ISSUE TITLE
DOCS add config load order edge cases

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-locator#200]
In some cases a config file may be loaded before the module's config file, causing things like the `infoWindowTemplate` and `listTemplate` custom values to be reset by the modules config. We'll need to add this to common issues docs describing how to fix it:

```yml
---
name: my-locator-config
after:
  - 'locator'
---
```
