### ISSUE TITLE
Map buttons don't work properly

### ISSUE THREAD

**Issue by kenlog** [dynamic/silverstripe-locator#224]
**Describe the bug**
The map buttons are not working properly, they are always loading, what is it due?
Thank you very much!

``` 
"silverstripe/recipe-cms": "4.6.0@stable"   
"dynamic/silverstripe-locator": "3.1.1"
```

**Screenshots**
![map](https://user-images.githubusercontent.com/11728231/88081947-67bed200-cb81-11ea-9382-a88c0ae62f01.gif)

**Comment by mak001** [comment]
This is possibly caused by a theme, like simple, adding a background images to image tags.
This can potentially be solved by adding this css to the site:
```css
.locator-map img {
    background: none;
    border: none;
}
```

**Comment by kenlog** [comment]
Hi @mak001 thank you your suggestion was helpful but I had to overwrite it like this:

```css
.typography img {
	background: none!important;
	border: none!important;
}  
```
